Search.appendIndex(
    [
                {
            "fqsen": "\\Ren\\ProtocolizedServer\\ProtocolizedServerClient",
            "name": "ProtocolizedServerClient",
            "summary": "Protocolized\u0020server\u0020client\u0020class\u0020with\u0020data\u002Dstoring\u0020and\u0020connection\u0020management\u0020capabilities",
            "url": "classes/Ren-ProtocolizedServer-ProtocolizedServerClient.html"
        },                {
            "fqsen": "\\Ren\\ProtocolizedServer\\ProtocolizedServerClient\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Protocolized\u0020server\u0020client\u0020object\u0020constructor",
            "url": "classes/Ren-ProtocolizedServer-ProtocolizedServerClient.html#method___construct"
        },                {
            "fqsen": "\\Ren\\ProtocolizedServer\\ProtocolizedServerClient\u003A\u003AsetData\u0028\u0029",
            "name": "setData",
            "summary": "Stores\u0020data\u0020by\u0020key",
            "url": "classes/Ren-ProtocolizedServer-ProtocolizedServerClient.html#method_setData"
        },                {
            "fqsen": "\\Ren\\ProtocolizedServer\\ProtocolizedServerClient\u003A\u003AgetData\u0028\u0029",
            "name": "getData",
            "summary": "Retrieves\u0020stored\u0020data\u0020by\u0020key\u0020or\u0020returns\u0020default\u0020if\u0020it\u0027s\u0020not\u0020exists",
            "url": "classes/Ren-ProtocolizedServer-ProtocolizedServerClient.html#method_getData"
        },                {
            "fqsen": "\\Ren\\ProtocolizedServer\\ProtocolizedServerClient\u003A\u003Awrite\u0028\u0029",
            "name": "write",
            "summary": "Writes\u0020data\u0020to\u0020connection",
            "url": "classes/Ren-ProtocolizedServer-ProtocolizedServerClient.html#method_write"
        },                {
            "fqsen": "\\Ren\\ProtocolizedServer\\ProtocolizedServerClient\u003A\u003Aclose\u0028\u0029",
            "name": "close",
            "summary": "Closes\u0020connection",
            "url": "classes/Ren-ProtocolizedServer-ProtocolizedServerClient.html#method_close"
        },                {
            "fqsen": "\\Ren\\ProtocolizedServer\\ProtocolizedServerClient\u003A\u003A\u0024connection",
            "name": "connection",
            "summary": "",
            "url": "classes/Ren-ProtocolizedServer-ProtocolizedServerClient.html#property_connection"
        },                {
            "fqsen": "\\Ren\\ProtocolizedServer\\ProtocolizedServerClient\u003A\u003A\u0024data",
            "name": "data",
            "summary": "",
            "url": "classes/Ren-ProtocolizedServer-ProtocolizedServerClient.html#property_data"
        },                {
            "fqsen": "\\Ren\\ProtocolizedServer\\ProtocolizedServerTraitInterface",
            "name": "ProtocolizedServerTraitInterface",
            "summary": "Protocolized\u0020server\u0020interface\u0020for\u0020traits",
            "url": "classes/Ren-ProtocolizedServer-ProtocolizedServerTraitInterface.html"
        },                {
            "fqsen": "\\Ren\\ProtocolizedServer\\ProtocolizedServerTraitInterface\u003A\u003Astart\u0028\u0029",
            "name": "start",
            "summary": "Server\u0020start\u0020function",
            "url": "classes/Ren-ProtocolizedServer-ProtocolizedServerTraitInterface.html#method_start"
        },                {
            "fqsen": "\\Ren\\ProtocolizedServer\\ProtocolizedServerTraitInterface\u003A\u003Aclose\u0028\u0029",
            "name": "close",
            "summary": "Server\u0020close\u0020function",
            "url": "classes/Ren-ProtocolizedServer-ProtocolizedServerTraitInterface.html#method_close"
        },                {
            "fqsen": "\\Ren\\ProtocolizedServer\\ProtocolizedServerTraitInterface\u003A\u003AregisterHandlers\u0028\u0029",
            "name": "registerHandlers",
            "summary": "Register\u0020packet\u0020handlers\u0020function",
            "url": "classes/Ren-ProtocolizedServer-ProtocolizedServerTraitInterface.html#method_registerHandlers"
        },                {
            "fqsen": "\\Ren\\ProtocolizedServer\\ProtocolizedServerTraitInterface\u003A\u003AonDataRead\u0028\u0029",
            "name": "onDataRead",
            "summary": "Packet\u0020parse\u0020function",
            "url": "classes/Ren-ProtocolizedServer-ProtocolizedServerTraitInterface.html#method_onDataRead"
        },                {
            "fqsen": "\\Ren\\ProtocolizedServer\\ProtocolizedServerTraitInterface\u003A\u003AonConnection\u0028\u0029",
            "name": "onConnection",
            "summary": "On\u0020new\u0020connection\u0020function",
            "url": "classes/Ren-ProtocolizedServer-ProtocolizedServerTraitInterface.html#method_onConnection"
        },                {
            "fqsen": "\\Ren\\ProtocolizedServer\\ProtocolizedServerTraitInterface\u003A\u003AonError\u0028\u0029",
            "name": "onError",
            "summary": "On\u0020new\u0020error\u0020function",
            "url": "classes/Ren-ProtocolizedServer-ProtocolizedServerTraitInterface.html#method_onError"
        },                {
            "fqsen": "\\Ren\\ProtocolizedServer\\ProtocolizedServerTraitInterface\u003A\u003A\u0024handlers",
            "name": "handlers",
            "summary": "Array\u0020of\u0020handlers",
            "url": "classes/Ren-ProtocolizedServer-ProtocolizedServerTraitInterface.html#property_handlers"
        },                {
            "fqsen": "\\Ren\\ProtocolizedServer\\ProtocolizedServerTraitInterface\u003A\u003A\u0024server",
            "name": "server",
            "summary": "Protocolized\u0020server\u0020object",
            "url": "classes/Ren-ProtocolizedServer-ProtocolizedServerTraitInterface.html#property_server"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Ren\\ProtocolizedServer",
            "name": "ProtocolizedServer",
            "summary": "",
            "url": "namespaces/ren-protocolizedserver.html"
        },                {
            "fqsen": "\\Ren",
            "name": "Ren",
            "summary": "",
            "url": "namespaces/ren.html"
        }            ]
);
